workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        
        publishing: 
            email:
                recipients:
                    - bjd00j@gmail.com.com
            # notify:
            #     success: true
            #     failure: false