workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        
    publishing: 
        email:
            recipients:
                - user_1@example.com
                - user_2@example.com
        notify:
            success: true
            failure: false